<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\avatar.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="C1.Xaml.WPF.FlexChart" Version="4.6.20231.784" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\avatar.png" />
  </ItemGroup>

</Project>